//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSportsNewsBot.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ESportsNewsContext : DbContext
    {
        public ESportsNewsContext()
            : base("name=ESportsNewsContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<Game> Games { get; set; }
        public virtual DbSet<RedditPost> RedditPosts { get; set; }
        public virtual DbSet<Subreddit> Subreddits { get; set; }
        public virtual DbSet<SubredditWebsite> SubredditWebsites { get; set; }
        public virtual DbSet<Website> Websites { get; set; }
        public virtual DbSet<ServiceApp> ServiceApps { get; set; }
    }
}
