//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSportsNewsBot.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Website
    {
        public System.Guid WebsiteID { get; set; }
        public Nullable<System.Guid> GameID { get; set; }
        public string Title { get; set; }
        public string URL { get; set; }
        public bool Active { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
